/* Generated by tools/scan-images.sh — do not edit by hand.
   Baked-in dimensions let main.js size a piece correctly on its first
   frame, before the file itself has finished decoding. */
const SIZES = {
  "215-poster-mockup-01-WEB.png": [640, 420],
  "470457316_1149641020173673_4614411694490972186_n-WEB.png": [1440, 961],
  "AA061221DB0015-WEB.png": [1440, 960],
  "AA061221DB0130-WEB.jpg": [1440, 960],
  "Business-Card-Mockup---Scene-3-WEB.jpg": [1440, 960],
  "Chart-Studio-WEB.jpg": [1240, 1024],
  "DSCF3906-WEB.jpg": [1440, 960],
  "GSM_Exhibits_CommentatorBooth_Mates-8387-1536x1025-WEB.jpg": [1240, 828],
  "GSM_Exhibits_Newstand_GameDay-9356-scaled-WEB.jpg": [1440, 961],
  "MAXME-x2-1-WEB.jpg": [1600, 551],
  "MAXME-x2-2-WEB.jpg": [3876, 1335],
  "POM-EXPLANATION-WEB.jpg": [1440, 1019],
  "PWC-Melb-6061-HiRes_WEB-WEB.jpg": [1440, 961],
  "PWC-Melb-7381-HiRes-WEB.jpg": [960, 1438],
  "PWC-Syd-9567-HiRes-V2-WEB.jpg": [960, 1438],
  "PWC-Syd-9666-1-HiRes-WEB.jpg": [960, 1438],
  "Percolare-DevicesMockup-WEB.jpg": [1240, 1264],
  "Responsive-Device-Mock-Up-Maxme-WEB.jpg": [1440, 960],
  "Responsive-Device-Mock-Up-PoM-WEB.jpg": [1440, 960],
  "Road-Safety-1-web-WEB.jpg": [1240, 827],
  "Screen-Shot-2021-01-10-at-11.06.02-am-gigapixel-very_compressed-scale-2_00x-WEB.jpg": [1440, 810],
  "Screen-Shot-2021-01-10-at-11.07.01-am-copy-gigapixel-very_compressed-scale-2_00x-WEB.jpg": [7680, 4302],
  "Syndica-Front-WEB.jpg": [1440, 1019],
  "UNRETOUCHED-6207-WEB.jpg": [720, 720],
};
