#!/usr/bin/env bash
# Regenerate js/sizes.js from whatever is in images/.
# Run after adding or replacing files:  ./tools/scan-images.sh
set -euo pipefail
cd "$(dirname "$0")/.."

out="js/sizes.js"
tmp="$(mktemp)"
portrait=0; landscape=0; square=0

{
  echo "/* Generated by tools/scan-images.sh — do not edit by hand."
  echo "   Baked-in dimensions let main.js size a piece correctly on its first"
  echo "   frame, before the file itself has finished decoding. */"
  echo "const SIZES = {"
} > "$tmp"

for f in images/*; do
  [ -f "$f" ] || continue
  case "${f##*.}" in
    jpg|jpeg|JPG|JPEG|png|PNG|gif|GIF|webp|WEBP|heic|HEIC) ;;
    *) continue ;;
  esac
  dims=$(sips -g pixelWidth -g pixelHeight "$f" 2>/dev/null) || continue
  w=$(printf '%s\n' "$dims" | awk '/pixelWidth/{print $2}')
  h=$(printf '%s\n' "$dims" | awk '/pixelHeight/{print $2}')
  [ -n "$w" ] && [ -n "$h" ] || continue
  printf '  "%s": [%s, %s],\n' "$(basename "$f")" "$w" "$h" >> "$tmp"
  ratio=$(awk -v w="$w" -v h="$h" 'BEGIN{printf "%.3f", h/w}')
  if   awk -v r="$ratio" 'BEGIN{exit !(r > 1.15)}'; then portrait=$((portrait+1))
  elif awk -v r="$ratio" 'BEGIN{exit !(r < 0.87)}'; then landscape=$((landscape+1))
  else square=$((square+1)); fi
done

echo "};" >> "$tmp"
mv "$tmp" "$out"

echo "wrote $out — $landscape landscape, $portrait portrait, $square square" >&2
